#!/usr/bin/env bash

if [ ! -n "$1" ]
then
  echo "error: Parameter project_group and project_name  not found"
  #echo -e "Usage: nginx-add-project [OPTIONS] [PROJECT_NAME]\n\nOptions:\n   -s, --share   Create project shred on PROJECT_NAME.d.shogo-test.ru"
  echo -e "Usage: nginx-add-project [PROJECT_GROUP] [PROJECT_NAME]"
  exit 1
fi

if [ ! -n "$2" ]
then
  echo "error: Parameter project_name not found"
  #echo -e "Usage: nginx-add-project [OPTIONS] [PROJECT_NAME]\n\nOptions:\n   -s, --share   Create project shred on PROJECT_NAME.d.shogo-test.ru"
  echo -e "Usage: nginx-add-project [PROJECT_GROUP] [PROJECT_NAME]"
  exit 1
fi

PROJECT_GROUP=$1
PROJECT_NAME=$2
templateConfigFile="/var/www/laradock/nginx/template_argilla.conf.example"
configFile="/var/www/laradock/nginx/sites/$PROJECT_NAME.conf"

if [ -e "$configFile" ]
then
   echo "Config $configFile already exists"
   exit 1
fi

#logPath="/var/www/laradock/logs/nginx/$PROJECT_NAME"
#mkdir $logPath
#chmod 777 $logPath

sed -e "s/project_name/$PROJECT_NAME/g" -e "s/project_group/$PROJECT_GROUP/g" $templateConfigFile > $configFile

#sed "s/project_name/$PROJECT_NAME/" $templateConfigFile > $configFile
#sed "s/project_group/$PROJECT_GROUP/" $configFile > $configFile

cd /var/www/laradock
docker-compose restart nginx

echo "complited"

